development:
  adapter: postgresql
  encoding: unicode
  database: HoneHouse_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: HoneHouse_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: HoneHouse_production
  pool: 5
